# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignUpWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import hashlib
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, QRegExp
from PyQt5.QtGui import QRegExpValidator
from PyQt5.QtWidgets import QApplication, QWidget, QMessageBox, QLineEdit

from dbmanager import userDbManager

class Ui_Form(QWidget):
    student_signup_signal = pyqtSignal(str)

    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.userdb = userDbManager()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("background-color: rgb(247, 253, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(-1, 50, -1, 50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 5, -1, 5)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.signUpLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signUpLabel.sizePolicy().hasHeightForWidth())
        self.signUpLabel.setSizePolicy(sizePolicy)
        self.signUpLabel.setMinimumSize(QtCore.QSize(131, 41))
        self.signUpLabel.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.signUpLabel.setFont(font)
        self.signUpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.signUpLabel.setObjectName("signUpLabel")
        self.gridLayout.addWidget(self.signUpLabel, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setHorizontalSpacing(1)
        self.formLayout.setObjectName("formLayout")
        self.studentIdLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.studentIdLabel.sizePolicy().hasHeightForWidth())
        self.studentIdLabel.setSizePolicy(sizePolicy)
        self.studentIdLabel.setMinimumSize(QtCore.QSize(101, 31))
        self.studentIdLabel.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.studentIdLabel.setFont(font)
        self.studentIdLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.studentIdLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.studentIdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.studentIdLabel.setObjectName("studentIdLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.studentIdLabel)
        self.studentIdLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.studentIdLineEdit.sizePolicy().hasHeightForWidth())
        self.studentIdLineEdit.setSizePolicy(sizePolicy)
        self.studentIdLineEdit.setMinimumSize(QtCore.QSize(191, 31))
        self.studentIdLineEdit.setMaximumSize(QtCore.QSize(191, 31))
        self.studentIdLineEdit.setObjectName("studentIdLineEdit")
        self.studentIdLineEdit.setMaxLength(10)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.studentIdLineEdit)
        self.studentNameLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.studentNameLabel.sizePolicy().hasHeightForWidth())
        self.studentNameLabel.setSizePolicy(sizePolicy)
        self.studentNameLabel.setMinimumSize(QtCore.QSize(101, 31))
        self.studentNameLabel.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.studentNameLabel.setFont(font)
        self.studentNameLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.studentNameLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.studentNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.studentNameLabel.setObjectName("studentNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.studentNameLabel)
        self.studentNameLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.studentNameLineEdit.sizePolicy().hasHeightForWidth())
        self.studentNameLineEdit.setSizePolicy(sizePolicy)
        self.studentNameLineEdit.setMinimumSize(QtCore.QSize(191, 31))
        self.studentNameLineEdit.setMaximumSize(QtCore.QSize(191, 31))
        self.studentNameLineEdit.setObjectName("studentNameLineEdit")
        self.studentNameLineEdit.setMaxLength(10)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.studentNameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLabel.sizePolicy().hasHeightForWidth())
        self.passwordLabel.setSizePolicy(sizePolicy)
        self.passwordLabel.setMinimumSize(QtCore.QSize(101, 31))
        self.passwordLabel.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.passwordLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLineEdit.sizePolicy().hasHeightForWidth())
        self.passwordLineEdit.setSizePolicy(sizePolicy)
        self.passwordLineEdit.setMinimumSize(QtCore.QSize(191, 31))
        self.passwordLineEdit.setMaximumSize(QtCore.QSize(191, 31))
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.passwordLineEdit.setMaxLength(16)
        self.passwordLineEdit.setEchoMode(QLineEdit.Password)  # 设置密码隐藏
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.passwordConfirmLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordConfirmLabel.sizePolicy().hasHeightForWidth())
        self.passwordConfirmLabel.setSizePolicy(sizePolicy)
        self.passwordConfirmLabel.setMinimumSize(QtCore.QSize(101, 31))
        self.passwordConfirmLabel.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordConfirmLabel.setFont(font)
        self.passwordConfirmLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.passwordConfirmLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passwordConfirmLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordConfirmLabel.setObjectName("passwordConfirmLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passwordConfirmLabel)
        self.passwordConfirmLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordConfirmLineEdit.sizePolicy().hasHeightForWidth())
        self.passwordConfirmLineEdit.setSizePolicy(sizePolicy)
        self.passwordConfirmLineEdit.setMinimumSize(QtCore.QSize(191, 31))
        self.passwordConfirmLineEdit.setMaximumSize(QtCore.QSize(191, 31))
        self.passwordConfirmLineEdit.setObjectName("passwordConfirmLineEdit")
        self.passwordConfirmLineEdit.setMaxLength(16)
        self.passwordConfirmLineEdit.setEchoMode(QLineEdit.Password)  # 设置密码隐藏
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passwordConfirmLineEdit)
        self.signUpbutton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signUpbutton.sizePolicy().hasHeightForWidth())
        self.signUpbutton.setSizePolicy(sizePolicy)
        self.signUpbutton.setMinimumSize(QtCore.QSize(111, 31))
        self.signUpbutton.setMaximumSize(QtCore.QSize(111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.signUpbutton.setFont(font)
        self.signUpbutton.setObjectName("signUpbutton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.signUpbutton)
        self.gridLayout.addLayout(self.formLayout, 2, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)

        #设置验证
        reg = QRegExp("PB[0~9]{8}")
        pValidator = QRegExpValidator(self)
        pValidator.setRegExp(reg)
        self.studentIdLineEdit.setValidator(pValidator)

        reg = QRegExp("[a-zA-z0-9]+$")
        pValidator.setRegExp(reg)
        self.passwordLineEdit.setValidator(pValidator)
        self.passwordConfirmLineEdit.setValidator(pValidator)

        self.studentIdLineEdit.returnPressed.connect(self.SignUp)   #响应回车
        self.studentNameLineEdit.returnPressed.connect(self.SignUp)
        self.passwordLineEdit.returnPressed.connect(self.SignUp)
        self.passwordConfirmLineEdit.returnPressed.connect(self.SignUp)

        self.retranslateUi(Form)
        self.signUpbutton.clicked.connect(Form.SignUp)
        QtCore.QMetaObject.connectSlotsByName(Form)



    def SignUp(self):
        id = self.studentIdLineEdit.text()
        name = self.studentNameLineEdit.text()
        password = self.passwordLineEdit.text()
        passwordConfirm = self.passwordConfirmLineEdit.text()
        if (id == "" or name == "" or password == '' or passwordConfirm ==''):
            QMessageBox.warning(self,"警告", "表单不可为空，请重新输入",QMessageBox.Yes,QMessageBox.Yes)
            return
        elif(passwordConfirm != password):
            print(QMessageBox.warning(self, "警告", "两次输入密码不一致，请重新输入", QMessageBox.Yes, QMessageBox.Yes))
            return

        else:
            #使用 PyQt5.QtSql import QSqlDatabase, QSqlQuery 操作数据库
            # db = QSqlDatabase.addDatabase("QSQLITE")
            # db.setDatabaseName('./db/LibraryManagement.db')
            # db.open()
            # query = QSqlQuery()

            hl = hashlib.md5()
            hl.update(password.encode(encoding='utf-8'))
            md5password = hl.hexdigest()
            # sql = "SELECT * FROM user WHERE StudentId='%s'" % (id) #使用 PyQt5.QtSql import QSqlDatabase, QSqlQuery 操作数据库
            # query.exec_(sql)
            # if (query.next()):

            userdata = self.userdb.querybyUserid(id)  #使用Python 自带sqlite 实现
            print('-----',userdata)
            if (userdata):
                print(QMessageBox.warning(self, "警告", "该账号已存在,请重新输入", QMessageBox.Yes, QMessageBox.Yes))
                return
            else:
                # sql = "INSERT INTO user VALUES ('%s','%s','%s',0,0,0)" % (id, name, md5password) #使用 PyQt5.QtSql import QSqlDatabase, QSqlQuery 操作数据库
                # db.exec_(sql)
                # db.commit()

                self.userdb.addUser(id,name,md5password)

                print(QMessageBox.information(self, "提醒", "您已成功注册账号!", QMessageBox.Yes, QMessageBox.Yes))
                self.student_signup_signal.emit(id)

            #db.close()
            return

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "\"欢迎登陆图书馆管理系统\""))
        self.signUpLabel.setText(_translate("Form", "注  册"))
        self.studentIdLabel.setText(_translate("Form", "学    号："))
        self.studentNameLabel.setText(_translate("Form", "姓    名："))
        self.passwordLabel.setText(_translate("Form", "密    码："))
        self.passwordConfirmLabel.setText(_translate("Form", "确认密码："))
        self.signUpbutton.setText(_translate("Form", "注  册"))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    mainMindow = Ui_Form()
    mainMindow.show()
    sys.exit(app.exec_())