# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignInWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import hashlib
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QWidget, QApplication, QMessageBox, QLineEdit

from dbmanager import userDbManager


class Ui_Form(QWidget):
    is_admin_signal = pyqtSignal()
    is_student_signal = pyqtSignal(str)

    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.userdb = userDbManager()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("background-color: rgb(247, 253, 255);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 230)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(410, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.passwordLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLineEdit.sizePolicy().hasHeightForWidth())
        self.passwordLineEdit.setSizePolicy(sizePolicy)
        self.passwordLineEdit.setMinimumSize(QtCore.QSize(200, 31))
        self.passwordLineEdit.setMaximumSize(QtCore.QSize(200, 31))
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.passwordLineEdit.setEchoMode(QLineEdit.Password) #密码隐藏
        self.gridLayout.addWidget(self.passwordLineEdit, 1, 1, 1, 2)
        self.studentIdLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.studentIdLabel.sizePolicy().hasHeightForWidth())
        self.studentIdLabel.setSizePolicy(sizePolicy)
        self.studentIdLabel.setMinimumSize(QtCore.QSize(101, 31))
        self.studentIdLabel.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.studentIdLabel.setFont(font)
        self.studentIdLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.studentIdLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.studentIdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.studentIdLabel.setObjectName("studentIdLabel")
        self.gridLayout.addWidget(self.studentIdLabel, 0, 0, 1, 1)
        self.signcanclebutton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signcanclebutton.sizePolicy().hasHeightForWidth())
        self.signcanclebutton.setSizePolicy(sizePolicy)
        self.signcanclebutton.setMinimumSize(QtCore.QSize(80, 31))
        self.signcanclebutton.setMaximumSize(QtCore.QSize(80, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.signcanclebutton.setFont(font)
        self.signcanclebutton.setObjectName("signcanclebutton")
        self.gridLayout.addWidget(self.signcanclebutton, 2, 2, 1, 1)
        self.studentIdLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.studentIdLineEdit.sizePolicy().hasHeightForWidth())
        self.studentIdLineEdit.setSizePolicy(sizePolicy)
        self.studentIdLineEdit.setMinimumSize(QtCore.QSize(200, 31))
        self.studentIdLineEdit.setMaximumSize(QtCore.QSize(200, 31))
        self.studentIdLineEdit.setObjectName("studentIdLineEdit")
        self.gridLayout.addWidget(self.studentIdLineEdit, 0, 1, 1, 2)
        self.signInbutton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signInbutton.sizePolicy().hasHeightForWidth())
        self.signInbutton.setSizePolicy(sizePolicy)
        self.signInbutton.setMinimumSize(QtCore.QSize(80, 31))
        self.signInbutton.setMaximumSize(QtCore.QSize(80, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.signInbutton.setFont(font)
        self.signInbutton.setObjectName("signInbutton")
        self.gridLayout.addWidget(self.signInbutton, 2, 1, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLabel.sizePolicy().hasHeightForWidth())
        self.passwordLabel.setSizePolicy(sizePolicy)
        self.passwordLabel.setMinimumSize(QtCore.QSize(101, 31))
        self.passwordLabel.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.passwordLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.signInbutton.clicked.connect(Form.signInCheck)
        self.signcanclebutton.clicked.connect(Form.signInCancleReset)
        self.studentIdLineEdit.returnPressed.connect(Form.signInCheck)
        self.passwordLineEdit.returnPressed.connect(Form.signInCheck)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "\"欢迎使用图书馆管理系统\""))
        self.label.setText(_translate("Form", "欢迎使用MG图书馆管理系统"))
        self.studentIdLabel.setText(_translate("Form", "学    号："))
        self.signcanclebutton.setText(_translate("Form", "重 置"))
        self.signInbutton.setText(_translate("Form", "登  录"))
        self.passwordLabel.setText(_translate("Form", "密    码："))

    def signInCheck(self):
        id = self.studentIdLineEdit.text()
        password = self.passwordLineEdit.text()

        hl = hashlib.md5()
        hl.update(password.encode(encoding='utf-8'))
        md5password = hl.hexdigest()

        if (id == ''or password == ''):
            QMessageBox.warning(self, "警告", "账号和密码不可为空!", QMessageBox.Yes, QMessageBox.Yes)
            return
        else:
            check_user = self.userdb.querybyUserid(id)
            if (check_user):
                print(check_user[0][0])
                print(check_user[0][1])
                print(check_user[0][2])
                print(check_user[0][3])
                print(check_user[0][4])

                correct_password = check_user[0][2]
                print(check_user, correct_password, md5password)
                if (id == check_user[0][0] and md5password == correct_password):
                    if (check_user[0][3] == 1):
                        #self.is_admin_signal.emit()
                        print('管理员登录成功！')
                    else:
                        #self.is_student_signal.emit(id)
                        print('普通用户登录成功！')
                else:
                    print(QMessageBox.warning(self, "警告", "密码不正确！", QMessageBox.Yes, QMessageBox.Yes))

            else:
                print(QMessageBox.information(self, "提示", "该账号不存在,请重新输入!", QMessageBox.Yes))
                self.signInCancleReset()
        return


    def signInCancleReset(self):
        self.studentIdLineEdit.clear()
        self.passwordLineEdit.clear()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    mainMindow = Ui_Form()
    mainMindow.show()
    sys.exit(app.exec_())